Homework6
Denis-Rubtsov/Some-console-game pull request #5
Opened 2024-01-08 09:57 UTC by Denis-Rubtsov

Translated the interface into English and did the sixth homework

2024-01-09 16:30 UTC, Denis-Rubtsov commented
Прошу @drubtsov1 сделать код-ревью как можно быстрее

2024-01-09 18:46 UTC, drubtsov1 requested changes

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Characters/Assassin.cs
> +		public Assassin(string name, int hp = 100, int lvl = 1, int damage = 56, int attackSpeed = 2500) : base(hp, lvl, damage, name, new List<EquipmentSize>() { EquipmentSize.Medium, EquipmentSize.Large
Может лучше сделать virtual эти проперти в базовом классе и оверрайдить их в наследниках? Мне не нравится передача 100500 параметров через конструктор

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Characters/Player.cs
> +        AllowableSize = allowableSize;
давай AllowedSizes назовем

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Characters/Player.cs
> +        Console.WriteLine("Выберите item на продажу (номер, начиная с 1; 0 - все; -1 - отмена");
рофлишь?

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Characters/PlayerFactory.cs
> +            int attackSpeed = int.Parse(Console.ReadLine());
Давай уберем отсюда весь ввод из консоли

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Equipment/Armor.cs
> +        public EquipmentSize Size => _equipmentSize;
Зачем отдельно проперти и филд, когда можно сделать только проперти?

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Program.cs
> +                    Console.WriteLine("Heal? (1 - да, 2 - нет)");
very хороший translate to английский

2024-01-09 18:46 UTC, drubtsov1 commented on HomeworkConsoleGame/Characters/PlayerFactory.cs
> +            int attackSpeed = int.Parse(Console.ReadLine());
и вообще фабрику странно используешь

2024-01-10 10:45 UTC, Denis-Rubtsov commented
Все советы были услышаны. Иду переделывать

2024-01-10 10:45 UTC, closed without merging